import speedtest as stest
from internet_details import *

set_download_speed = 50
set_upload_speed = 50

servers = [3467, 10536, 4520,19356,6932] # Server id refer https://www.speedtest.net/speedtest-servers-static.php
threads = 2 # Number of thread test

s = stest.Speedtest()
s.get_servers(servers)
s.get_best_server()
s.download(threads=threads)
s.upload(threads=threads)
s.results.share() # Enable share

result = s.results.dict() 

def CheckConnectionIssueTicket():
    download = round(result['download']/1000000, 2) # Bits/s to MBp/s
    upload =  round(result['upload']/1000000, 2)
    ping =  round(result['ping'], 1)
    location = result['server']['name']
    host = result['server']['sponsor']
    client_ip = result['client']['ip']
    share_image = result['share']
    
    msg_footer = '\n\nPlease fix this issue ASAP. thank you\n\n--this message was auto-generated by a bot--'
    msg = 'Hi,\nMy internet connection is slow. The download speed was '+str(download)+'Mbps, upload was '+str(upload)+'Mbps when test was made from '+location+' hosted by '+host+'. My Public IP was '+client_ip+', refer '+share_image+' for more info.'+msg_footer

    if (download >= set_download_speed and upload >= set_upload_speed):
        print('Awesome! Your internet connection is fine, no issue ticket was created')
        print('Current download is '+str(download)+'Mbps, upload is '+str(upload)+'Mbps when test is made from '+location+' hosted by '+host)
    else:
        LoginVianet()
        driver.find_element(By.CSS_SELECTOR, '.btn').click()
        driver.find_element(By.ID, 'tab_addticket').click()
        t.sleep(0.5)
        driver.find_element(By.ID, 'description').click()
        driver.find_element(By.ID, 'description').send_keys(msg)
        print('Internet issue ticket is successfully created and posted as:\n\n'+msg+'\n')
    # driver.find_element(By.ID, 'submit_ticket').click() #submit_ticket
    driver.get('https://customers.vianet.com.np/customers/logout')

if __name__ == '__main__':
    CheckConnectionIssueTicket()
    driver.quit()